# Generated by Django 2.1.7 on 2019-04-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('isbn', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
